version: "3.2"
services:
    le:
        image: certbot/certbot
        entrypoint: certbot-auto certonly --standalone --email cert@vtx.sh -d vtx.sh 
    pgsql:
        image: postgres:9.6-alpine
        restart: always
        environment:
            POSTGRES_USER: xsshunter
            POSTGRES_DB: xsshunter
            POSTGRES_PASSWORD: xsshunter
    xsshunter:
        build: .
        restart: always
        environment:
            - DOMAIN=${DOMAIN}
            - EMAILFROM=${EMAILFROM}
            - MAILGUNKEY=${MAILGUNKEY}
            - MAILGUNDOM=${MAILGUNDOM}
            - ABUSEEMAIL=${ABUSEEMAIL}
            - COOKIESECRET=${COOKIESECRET}
        depends_on:
            - le
            - pgsql

# Run LE container to get certs
# Run PgSQL container to have a database
# Run XSS Hunter container to recieve payload calls
